name: python-hyperscan workflow
on: [push]
env:
  pcre-version: 8.45
  hyperscan-version: v5.4.0
jobs:
  compile-libraries:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [macos-latest]
    steps:
      - name: Cache pcre lib
        id: cache-pcre-macos
        uses: actions/cache@v3
        with:
          path: ~/pcre-lib
          key: pcre-lib-macos-${{ env.pcre-version }}

      - name: Build pcre on macos
        if: ${{ startsWith(matrix.platform, 'macos') && (steps.cache-pcre-macos.outputs.cache-hit != 'true') }}
        run: |
          wget -qO- https://sourceforge.net/projects/pcre/files/pcre/${{ env.pcre-version }}/pcre-${{ env.pcre-version }}.tar.gz/download | tar xvz
          mv pcre-${{ env.pcre-version }} pcre-lib
          cd pcre-lib
          sudo mkdir /opt/pcre-build
          ./configure --prefix=/opt/pcre-lib --enable-unicode-properties --enable-utf
          sudo make && sudo make install
          sudo mv /opt/pcre-build build
          cd ..
          mv pcre-lib ~/

      - name: Cache hyperscan lib
        id: cache-hyperscan-macos
        uses: actions/cache@v3
        with:
          path: ~/hyperscan-lib
          key: hyperscan-lib-mac-os-${{ env.hyperscan-version }}

      - name: Build hyperscan on macos
        if: ${{ startsWith(matrix.platform, 'macos') && (steps.cache-hyperscan-macos.outputs.cache-hit != 'true') }}
        run: |
          brew install cmake boost ragel
          git clone -b ${{ env.hyperscan-version }} https://github.com/intel/hyperscan.git
          mkdir -p hyperscan/build
          cd hyperscan/build
          sudo mkdir /opt/hyperscan-lib
          cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/hyperscan-lib -DBUILD_STATIC_AND_SHARED=ON -DPCRE_SOURCE=../../pcre-lib ../
          make && sudo make install
          sudo mv /opt/hyperscan-lib ~/
  build-wheels:
    runs-on: ${{ matrix.platform }}
    needs: compile-libraries
    strategy:
      matrix:
        # Only Linux is supported at the moment
        platform: [macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Cache pcre lib
        id: cache-pcre-macos
        uses: actions/cache@v3
        with:
          path: ~/pcre-lib
          key: pcre-lib-macos-${{ env.pcre-version }}
      - name: Cache hyperscan lib
        id: cache-hyperscan-macos
        uses: actions/cache@v3
        with:
          path: ~/hyperscan-lib
          key: hyperscan-lib-mac-os-${{ env.hyperscan-version }}
      - name: PCRE lib cache miss macos
        if: ${{ startsWith(matrix.platform, 'macos') && (steps.cache-pcre-macos.outputs.cache-hit != 'true') }}
        run: exit 1
      - name: Hyperscan lib cache miss macos
        if: ${{ startsWith(matrix.platform, 'macos') && (steps.cache-hyperscan-macos.outputs.cache-hit != 'true') }}
        run: exit 1
      - uses: actions/checkout@v2
      - name: Setup macos
        if: ${{ startsWith(matrix.platform, 'macos') }}
        run: |
          brew install clang-format
          echo "DYLD_FALLBACK_LIBRARY_PATH=$HOME/hyperscan-lib/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/hyperscan-lib/lib/pkgconfig:$HOME/pcre-lib/build/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=$HOME/hyperscan-lib/include/hs:$C_INCLUDE_PATH" >> $GITHUB_ENV
      - name: List lib 2
        run: ls ~/hyperscan-lib
      - name: List lib
        run: ls $HOME/hyperscan-lib
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.11"
      - name: Build and test
        run: |
          pip install -UI setuptools
          poetry install
          poetry build -vvv
          poetry run pytest -vvv tests/
      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.whl
            dist/*.tar.gz
